Session/2の追加
naruogram/Yumemi-iOS-Training pull request #2
Opened 2022-06-17 06:11 UTC by naruogram

**実際の画面**

https://user-images.githubusercontent.com/75286616/174235958-47a6a4b2-eb15-4ad1-8b0a-93d5a873c2c1.mp4

**実装したもの**

[Session2](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md)

追加した点

・APIの導入(YumemiWeather)

・画像の追加

・Reloadボタンを押した際にAPIの結果によって、画像が変更される仕様

レビューお願いします!

2022-06-17 07:27 UTC, ribilynn requested changes
いくつをコメントしました、よろしくおねがいします。

2022-06-17 07:27 UTC, ribilynn commented on Yumemi-iOS-Training/ViewController.swift
>      }
この関数だとただ `YumemiWeather.fetchWeatherCondition()` の包装なんで意味ありません。

もし、ViewController 内に「 YumemiWeather から天気状況を取得し、Image に変わって設置する」ということを共通化したいなら、こう書くべき：
```swift
public func fetchWeatherCondition() {
    let weather = YumemiWeather.fetchWeatherCondition()
    setImage(weather: weather)
}
```
で、他のところにこれを呼ぶ。

2022-06-17 07:27 UTC, ribilynn commented on Yumemi-iOS-Training/ViewController.swift
> +    }
動作を表す関数であれば、関数名を
- 動作っぽくにする（fetchSomething）
- didTapXXXButton

のどちらにしてください。


また、略語は避けるべきだと思います。
Swift 公式の [API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/) がおすすめです。
> Avoid abbreviations. Abbreviations, especially non-standard ones

2022-06-17 07:27 UTC, ribilynn commented on Yumemi-iOS-Training/Assets.xcassets/Cloudy.imageset/Contents.json
> +}
- Image Asset ３つともそうですけど、名前が大文字になったせいで、そもそも実行してボタン押しても画像が出ません。
- pdf のようなベクトル画像であれば、Single Scale にするべき。
<img src="https://user-images.githubusercontent.com/11924267/174247744-62d1d1ca-97d5-48da-bf87-1303c6cf1910.png" width="300">

2022-06-17 08:19 UTC, naruogram commented on Yumemi-iOS-Training/ViewController.swift
> +    }
勉強になります!
ありがとうございます!
API Design GuideLines読ませていただきます!

2022-06-17 08:21 UTC, naruogram commented
@ribilynn 

レビューありがとうございます!

再度修正しました!

**変更点**

・関数の共有化(指摘いただいた部分)
・タップした時の関数の命名変更
・画像の対応等

よろしくお願いいたします!

2022-06-20 02:22 UTC, naruogram commented
> @ribilynn
> 
> レビューありがとうございます!
> 
> 再度修正しました!
> 
> **変更点**
> 
> ・関数の共有化(指摘いただいた部分) ・タップした時の関数の命名変更 ・画像の対応等
> 
> よろしくお願いいたします!

追記 : enumで判別するように変更しました

2022-06-20 03:25 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/170465)

2022-06-20 04:59 UTC, merged