session6の追加
naruogram/Yumemi-iOS-Training pull request #7
Opened 2022-06-23 08:15 UTC by naruogram

**課題**

[session6](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/VC_Lifecycle.md)

**実際の画面**

https://user-images.githubusercontent.com/75286616/175250435-7feda493-de70-486a-9021-4c7f00b551b1.mp4

**実装した点**

・新たに画面の追加(黒背景)

・initialViewControllerという最初に呼ばれるviewControllerの追加

・closeを押したときの処理の追加

レビューお願いします!

2022-06-23 09:12 UTC, ribilynn requested changes
- 複数の ViewController がある以上、元の VC はより適切な命名にするべきです。
- Storyboard の整列：
    <img src="https://user-images.githubusercontent.com/11924267/175263040-069cb2b6-6213-4df9-b75d-690a44dce012.png" width="400">

2022-06-23 09:12 UTC, Lumisilk commented on Yumemi-iOS-Training/ViewController/ViewController.swift
> +
要らない空行。

2022-06-23 09:12 UTC, ribilynn commented on Yumemi-iOS-Training/ViewController/ViewController.swift
> +    }
- 実際はボタンの動作なのに didTap〜Page は…？
    前にも申し上げたんですが、
    - didTapCloseButton にするか
    - 動作っぽく backToPreviousPage にするか
- `self.` は要らないです

2022-06-23 09:12 UTC, ribilynn commented on Yumemi-iOS-Training/ViewController/InitialViewController.swift
> +    }
やることなければわざわざ書く必要はないです。そちらの ViewController も同じく。

2022-06-23 09:47 UTC, naruogram commented
@ribilynn 
レビューありがとうございます!

理解しきれていない部分がありましたが、レビューのおかげで理解できました。

修正点

・命名の変更
・不要部分の削除

再度、お時間ある時にレビューお願いします!

2022-06-24 00:08 UTC, ribilynn approved these changes
修正ありがとうございます
![LGTM](https://i.lgtm.fun/2001.gif)

2022-06-24 01:50 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/6028)

2022-06-24 05:39 UTC, merged